plugins:
    sonar-java:
      enabled: true
      config:
        sonar.java.source: "11"
        tests_patterns:
          - src/test/**
          - livraria/src/test/**
          - transportadora/src/test/**