spring:

  profiles:
<<<<<<< HEAD
    active: production
=======
    active: prod
>>>>>>> master

  datasource:
    url: $DATABASE_URL

  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: false

  jackson:
    deserialization:
      fail-on-unknown-properties: true
